### ISSUE TITLE
请问这个计算速度有多快啊，主要取决于什么因素呢？

### ISSUE THREAD

**Issue by sjbz** [hrpzcf/HashCalculator#1]
请问这个计算速度有多快啊，主要取决于什么因素呢？
我预计有将近四万个文件，每个文件300m以下，想要批量计算和校验完，但是不知道大概会花费多长时间
有没有大哥能够科普一下呢？或者说明一下计算的方法

**Comment by hrpzcf** [comment]
批量计算速度主要取决于硬盘读取速度，sha224算法在所有算法中也是计算速度最慢的。如果文件都在300M附近且是机械硬盘，建议设置同时计算文件数为2个或者1个，如果是读取速度3000M的固态硬盘，可以设置为同时计算8个或者4个。
建议先计算一两百个文件估算一下大概速度。

**Comment by sjbz** [comment]
> 批量计算速度主要取决于硬盘读取速度，sha224算法在所有算法中也是计算速度最慢的。如果文件都在300M附近且是机械硬盘，建议设置同时计算文件数为2个或者1个，如果是读取速度3000M的固态硬盘，可以设置为同时计算8个或者4个。 建议先计算一两百个文件估算一下大概速度。

我就算md5，然后文件都是存在外接的硬盘里（usb3.0接口），cpu的话 主频：2.6GHz 最大睿频：3.6GHz 内存16g
突发奇想，这个是不是可以再加个计算时间的一列，然后再加个开始计算和暂停计算的按钮
（理直气壮的幻想哈哈哈）

**Comment by hrpzcf** [comment]
加计算时间列和单个任务的开始和暂停之前就已经有计划了，但是没有时间写

**Comment by sjbz** [comment]
> 加计算时间列和单个任务的开始和暂停之前就已经有计划了，但是没有时间写

哈哈大佬加油

**Comment by NeviNospel** [comment]
AMD 5950x、PCIe 4.0 x4 NVMe SSD、8任务MD5并行hash，任务管理器显示硬盘读取速度为5.2GB/s
