### ISSUE TITLE
能否增加一个去重的功能

### ISSUE THREAD

**Issue by b3nguang** [hrpzcf/HashCalculator#17]
计算哈希后，能否去重

**Comment by hrpzcf** [comment]
可以具体描述一下吗？是从列表清除重复的项，还是删除重复的文件？

**Comment by b3nguang** [comment]
删除重复的文件。比如我有两个哈希一样的文件，1.txt  2.txt，在经过软件计算哈希后，删除哈希一样的文件，但是要保留一个文件，也就是说删除2.txt，保留1.txt

**Comment by hrpzcf** [comment]
你好，你请求的功能在 5.0.0-beta1 版本中已实现，使用步骤：
1. 批量计算文件哈希值
2. 点击主窗口上方【筛选】按钮打开筛选面板，勾选【相同哈希值】筛选器，选择步骤 1 中任意一个已计算的算法类型，勾选【排除重复计算或不存在的文件】，然后点击筛选面板右边的【刷新】按钮筛选出相同哈希值的文件
3. 点击下方【删除文件】命令的【选择】按钮，主窗口会出现【删除】列用于勾选要删除的文件，程序会自动勾选多余的文件，如果你对程序自动勾选的结果不满意，也可以手动更改勾选的文件
4. 点击筛选面板的【删除文件】命令的【删除】按钮，多余的文件将被移动到回收站，如果发现误删了文件，可以从回收站恢复文件
