### ISSUE TITLE
请求增加xxHash算法支持

### ISSUE THREAD

**Issue by bohong65** [hrpzcf/HashCalculator#29]
对于大量文件hash计算，速度是很影响体验的问题，目前开源hash算法xxHash速度明显领先于其他算法，也有对应c/c++库，希望能在后续版本增加对这一算法的支持。xxHash项目地址：https://github.com/Cyan4973/xxHash

**Comment by hrpzcf** [comment]
现在用的 BouncyCastle 速度确实比同类库要慢很多，我先研究研究 xxHash

**Comment by hrpzcf** [comment]
目前个人能力有限，没有找到好的方法既能调用 xxhash 的 c 库又能保持 HashCalculator 的单文件特点，所以暂时使用 C# 的 xxhash 实现，速度与 xxhsum.exe 差距相当大，后续会考虑找更好的办法使用 xxhash 的 C 库或者直接使用 xxhsum.exe

**Comment by bohong65** [comment]
> 目前个人能力有限，没有找到好的方法既能调用 xxhash 的 c 库又能保持 HashCalculator 的单文件特点，所以暂时使用 C# 的 xxhash 实现，速度与 xxhsum.exe 差距相当大，后续会考虑找更好的办法使用 xxhash 的 C 库或者直接使用 xxhsum.exe

感谢适配，辛苦啦

**Comment by hrpzcf** [comment]
XxHash 算法已经改为调用 XxHash 的 C 库 Api 来计算，要计算的文件在机械硬盘上时由于读取速度是瓶颈，没有与之前版本的 C# 实现拉开差距，但是在固态硬盘上速度提升很大，计算 5.3GB 的文件，冷启动时可以在 5 秒内完成计算，再次计算可以在 2 秒左右完成。
