### ISSUE TITLE
内容显示有问题

### ISSUE THREAD

**Issue by smdx** [hrpzcf/HashCalculator#4]
你好，在校验结果显示那里算法和输出栏显示不全。

系统：Win11 Pro 22623.1180
APP版本：v4.4.0
屏幕4K分辨率、系统缩放150%
![Screenshot-2023-07-20_102140](https://github.com/hrpzcf/HashCalculator/assets/9279217/240d755d-78bf-43e5-9652-7170f47a9c9f)

PS:请问可以增加多个算法校验功能吗？谢谢
类似7zip这种
![Screenshot-2023-07-20_102936](https://github.com/hrpzcf/HashCalculator/assets/9279217/a8c90ab6-880f-4d52-b7b3-6b77b1f7101a)

**Comment by hrpzcf** [comment]
让我先研究一下  😂

**Comment by hrpzcf** [comment]
我用1080p的显示器在各种缩放倍率下都没有成功复现文字显示不全的问题（没有4k显示器），请问这个问题是稳定存在的还是在特定操作下才出现的？
<img width="960" alt="屏幕截图 2023-07-20 125538" src="https://github.com/hrpzcf/HashCalculator/assets/58855572/e35a6736-8d70-4dd9-a03d-638a2b70da1d">

**Comment by smdx** [comment]
> 我用1080p的显示器在各种缩放倍率下都没有成功复现文字显示不全的问题（没有4k显示器），请问这个问题是稳定存在的还是在特定操作下才出现的？ <img alt="屏幕截图 2023-07-20 125538" width="960" src="https://user-images.githubusercontent.com/58855572/254794248-e35a6736-8d70-4dd9-a03d-638a2b70da1d.png">

我把缩放比例调100%重启系统后显示正常了，然后再调150%重启后也没问题了。很神奇

**Comment by smdx** [comment]
> 我用1080p的显示器在各种缩放倍率下都没有成功复现文字显示不全的问题（没有4k显示器），请问这个问题是稳定存在的还是在特定操作下才出现的？ <img alt="屏幕截图 2023-07-20 125538" width="960" src="https://user-images.githubusercontent.com/58855572/254794248-e35a6736-8d70-4dd9-a03d-638a2b70da1d.png">

找到原因了，改过系统字体大小设置系统缩放后字体大小还原了APP的界面就没问题。重新设置大小就会出现这个问题。
![Screenshot-2023-07-20_174534](https://github.com/hrpzcf/HashCalculator/assets/9279217/a9727301-39bf-4496-8ace-a7b03e7b2ef4)

**Comment by hrpzcf** [comment]
> > 我用1080p的显示器在各种缩放倍率下都没有成功复现文字显示不全的问题（没有4k显示器），请问这个问题是稳定存在的还是在特定操作下才出现的？ <img alt="屏幕截图 2023-07-20 125538" width="960" src="https://user-images.githubusercontent.com/58855572/254794248-e35a6736-8d70-4dd9-a03d-638a2b70da1d.png">
> 
> 找到原因了，改过系统字体大小设置系统缩放后字体大小还原了APP的界面就没问题。重新设置大小就会出现这个问题。 ![Screenshot-2023-07-20_174534](https://user-images.githubusercontent.com/9279217/254845162-a9727301-39bf-4496-8ace-a7b03e7b2ef4.jpg)

应该是和系统缩放功能冲突了

**Comment by smdx** [comment]
应该是修改字体大小后超过APP显示框了...

**Comment by hrpzcf** [comment]
试试这个能不能解决问题：[HashCalculator-4.4.0-2307201815](https://wwbo.lanzouy.com/i4pkA13116zi)

**Comment by smdx** [comment]
> 试试这个能不能解决问题：[HashCalculator-4.4.0-2307201815](https://wwbo.lanzouy.com/i4pkA13116zi)

谢谢，我下载试了字体还是超出了显示框

**Comment by hrpzcf** [comment]
你好，你请求的【同时校验多个算法校验】功能已经在 5.0.0-beta1 版本中实现。
