### ISSUE TITLE
哈希校验依据打开功能可以自动匹配吗？

### ISSUE THREAD

**Issue by smdx** [hrpzcf/HashCalculator#47]
你好，在设置了多个默认哈希算法时使用哈希校验依据打开功能校验结果需要手动选择类型。
例如默认哈希算法选择了MD5、Crc32、SHA-256、SHA-512。校验依据哈希值是SHA-256
使用哈希校验依据打开功能校验结果默认是MD5，可以设置成校验结果自动匹配校验依据吗？谢谢

![Screenshot-2023-11-24_150757](https://github.com/hrpzcf/HashCalculator/assets/9279217/052e8f9a-4cf5-4714-99a5-feca70ea00ee)

**Comment by hrpzcf** [comment]
> 可以设置成校验结果自动匹配校验依据吗？
你的意思是根据哈希值清单（校验依据文件）里哈希值的长度，自动从已勾选的默认算法中选择可以生成相同长度哈希值的算法来计算文件的哈希值吗？这个应该可以实现。
还有个方案是给【作为哈希校验依据打开】右键菜单增加算法子菜单，让用户自行选择使用哪个算法来进行计算。

**Comment by smdx** [comment]
> > 可以设置成校验结果自动匹配校验依据吗？
> 
> 你的意思是根据哈希值清单（校验依据文件）里哈希值的长度，自动从已勾选的默认算法中选择可以生成相同长度哈希值的算法来计算文件的哈希值吗？这个应该可以实现。
> 
> 还有个方案是给【作为哈希校验依据打开】右键菜单增加算法子菜单，让用户自行选择使用哪个算法来进行计算。

对，就是这个意思。使用校验依据文件进行校验时自动匹配对应的算法显示结果。

**Comment by hrpzcf** [comment]
> > > 可以设置成校验结果自动匹配校验依据吗？
> > 
> > 
> > 你的意思是根据哈希值清单（校验依据文件）里哈希值的长度，自动从已勾选的默认算法中选择可以生成相同长度哈希值的算法来计算文件的哈希值吗？这个应该可以实现。
> > 还有个方案是给【作为哈希校验依据打开】右键菜单增加算法子菜单，让用户自行选择使用哪个算法来进行计算。
> 
> 对，就是这个意思。使用校验依据文件进行校验时自动匹配对应的算法显示结果。

5.9版本已发布，在旧版卸载右键菜单后在新版重新安装右键菜单，打开校验依据文件时选择“作为校验依据打开”→“自动选择”即可自动按依据文件中的哈希值长度匹配算法（需要在设置“当校验依据文件中未指明算法”里选择合适的选项）

**Comment by smdx** [comment]
大佬你好，使用了两天反馈一下。2级菜单感觉有点繁琐，是不是可以把打开校验依据文件时选择“作为校验依据打开”功能在设置里面增加一个选项，开启相关选项就直接像以前那样选择“作为校验依据打开”直接按“自动选择”算法开始校验数据，关闭相关选项后提供2级菜单可选择算法校验？谢谢

**Comment by hrpzcf** [comment]
> @hrpzcf 大佬你好，使用了两天反馈一下。2级菜单感觉有点繁琐，是不是可以把打开校验依据文件时选择“作为校验依据打开”功能在设置里面增加一个选项，开启相关选项就直接像以前那样选择“作为校验依据打开”直接按“自动选择”算法开始校验数据，关闭相关选项后提供2级菜单可选择算法校验？谢谢

我现在在考虑做自定义系统右键菜单功能，不过可能要很久以后才能做出来。发一个特别版给你先过渡一下吧 [HashCalculator-5.9.0_shell-5.8.0](https://wwbo.lanzouy.com/i1Sgq1gkooqh)

**Comment by smdx** [comment]
> > @hrpzcf 大佬你好，使用了两天反馈一下。2级菜单感觉有点繁琐，是不是可以把打开校验依据文件时选择“作为校验依据打开”功能在设置里面增加一个选项，开启相关选项就直接像以前那样选择“作为校验依据打开”直接按“自动选择”算法开始校验数据，关闭相关选项后提供2级菜单可选择算法校验？谢谢
> 
> 我现在在考虑做自定义系统右键菜单功能，不过可能要很久以后才能做出来。发一个特别版给你先过渡一下吧 [HashCalculator-5.9.0_shell-5.8.0](https://wwbo.lanzouy.com/i1Sgq1gkooqh)

下载使用了，非常好。感谢
