### ISSUE TITLE
直接选择校验依据进行校验问题

### ISSUE THREAD

**Issue by smdx** [hrpzcf/HashCalculator#5]
大佬你好，直接选择校验依据进行校验这个功能需要打开app界面选择校验依据文件，可以增加个可选功能在资源管理器对sha256sums这类校验依据右键计算哈希值时直接以依据进行校验吗？这样不用打开app界面再进行操作。谢谢
![Screenshot-2023-07-22_191558](https://github.com/hrpzcf/HashCalculator/assets/9279217/d906daa0-63cb-43f8-9354-660399bb1b0d)

**Comment by hrpzcf** [comment]
后续版本会添加《作为哈希值校验依据打开》这样的选项的。
最新代码中与这个功能的相关逻辑已经完成了，只差一个右键菜单选项，还可以设置关联 .hcb 文件（内容与 sha256sums 之类的文件相同，仅扩展名不同），可以直接双击打开进行校验。

**Comment by smdx** [comment]
这样就太棒了，期待版本更新。那我就关闭这个issue了

**Comment by hrpzcf** [comment]
> 这样就太棒了，期待版本更新。那我就关闭这个issue了

没关系不用关，我搞定了功能会关的😊
