### ISSUE TITLE
复制失败

### ISSUE THREAD

**Issue by Traveller1314** [hrpzcf/HashCalculator#50]
复制失败
错误详情: OpenClipboard 失败(异常来自 HRESULT:0x800401D0
(CLIPBRD E CANT OPEN))
![Uploading 微信截图_20231130171734.png…]()

**Comment by Traveller1314** [comment]
截图 https://imgse.com/i/pirapTg

**Comment by hrpzcf** [comment]
是每次点击复制按钮都会出现这个错误还是偶尔出现？偶尔出现的话可能是因为多次点击间隔太短导致的

**Comment by Traveller1314** [comment]
测试了一下，在小米电脑管家打开的时候，是会出现这种错误的，只有退出小米电脑助手后就能正常使用

**Comment by hrpzcf** [comment]
我没有安装小米电脑管家，没有办法测试是否解决了问题，你可以下载这个版本 [HashCalculator-5.9.0-231209](https://wwbo.lanzouy.com/iXUYz1hac2ud) 测试一下吗？

**Comment by Traveller1314** [comment]
可以了  不报错
