### ISSUE TITLE
安装右击菜单失败

### ISSUE THREAD

**Issue by eiheiheiOwO** [hrpzcf/HashCalculator#6]
![image](https://github.com/hrpzcf/HashCalculator/assets/31793442/e6b0e4ef-0bb0-452a-a475-b87984e520f3)

**Comment by hrpzcf** [comment]
你好，请问你的系统注册表是否有`HKEY_CURRENT_USER\Software\Classes\Applications`这个注册表路径？我猜测可能是因为`Applications`这个注册表项不存在，而当前版本没有选择创建这个项导致的失败。
