### ISSUE TITLE
5.14.0无法导出结果

### ISSUE THREAD

**Issue by BattlefieldFlying** [hrpzcf/HashCalculator#67]
5.14.0无法导出结果，提示哈希值导出失败，异常信息：系统找不到指定的驱动器，5.13.1、4.5.1可以正常导出结果，其他版本没有尝试，不知道是BUG还是我电脑系统的问题或设置的问题
![QQ截图20240128163529](https://github.com/hrpzcf/HashCalculator/assets/149608262/302a673a-3bcf-4c57-a01d-31a34cf7750a)

**Comment by hrpzcf** [comment]
我测试了导出功能，没有发现相同的问题。是不是你的保存位置比较特殊，比如保存位置不是本地硬盘？
我对比了5.13.1和5.14.0版本的代码，但是由于5.14.0版本对导出功能做了很多修改，代码比较乱，暂时没发现明显会导致出现这个问题的原因。
这个是按照猜测修改的版本，你试试可以正常使用导出功能吗？[HashCaclulator-5.14.0-240131](https://wwk.lanzouo.com/iK5lx1ms9u5g
)

**Comment by BattlefieldFlying** [comment]
> 我测试了导出功能，没有发现相同的问题。是不是你的保存位置比较特殊，比如保存位置不是本地硬盘？ 我对比了5.13.1和5.14.0版本的代码，但是由于5.14.0版本对导出功能做了很多修改，代码比较乱，暂时没发现明显会导致出现这个问题的原因。 这个是按照猜测修改的版本，你试试可以正常使用导出功能吗？[HashCaclulator-5.14.0-240131](https://wwk.lanzouo.com/iK5lx1ms9u5g)

感谢大佬，我经过测试发现了问题所在，应该是软件会记录上一次导出结果的位置，我之前最后一次是往移动硬盘里导出结果，现在移除了移动硬盘导致路径不存在就会出现这种情况，5.14是会提示这个，之前的版本应该没有这提醒但是会卡死或闪退。

**Comment by BattlefieldFlying** [comment]
> 我测试了导出功能，没有发现相同的问题。是不是你的保存位置比较特殊，比如保存位置不是本地硬盘？ 我对比了5.13.1和5.14.0版本的代码，但是由于5.14.0版本对导出功能做了很多修改，代码比较乱，暂时没发现明显会导致出现这个问题的原因。 这个是按照猜测修改的版本，你试试可以正常使用导出功能吗？[HashCaclulator-5.14.0-240131](https://wwk.lanzouo.com/iK5lx1ms9u5g)

感谢大佬，我经过测试发现了问题所在，应该是软件会记录上一次导出结果的位置，我之前最后一次是往移动硬盘里导出结果，现在移除了移动硬盘导致路径不存在就会出现这种情况，5.14是会提示这个，之前的版本应该没有这提醒但是会卡死或闪退。

**Comment by BattlefieldFlying** [comment]
> 我测试了导出功能，没有发现相同的问题。是不是你的保存位置比较特殊，比如保存位置不是本地硬盘？ 我对比了5.13.1和5.14.0版本的代码，但是由于5.14.0版本对导出功能做了很多修改，代码比较乱，暂时没发现明显会导致出现这个问题的原因。 这个是按照猜测修改的版本，你试试可以正常使用导出功能吗？[HashCaclulator-5.14.0-240131](https://wwk.lanzouo.com/iK5lx1ms9u5g)

其他版本之前出现卡死我强制结束进程后使其记录的路径重置了，我因此才以为是只有5.14有这问题
