### ISSUE TITLE
作者可不可以增加一个批量改哈希值的功能，最好是不用计算直接改的那种

### ISSUE THREAD

**Issue by API2019** [hrpzcf/HashCalculator#68]
作者可不可以增加一个批量改哈希值的功能，最好是不用计算直接改的那种

**Comment by hrpzcf** [comment]
功能已实现，需要调整一些设置项来实现：
1. 找到【任务设置选项】页的【文件被添加后自动启动对该文件的计算任务】，取消勾选
2. 通过【选择文件】或【选择文件夹】按钮、拖动文件到表格等方式添加文件（不要开始计算）
3. 使用【添加标记改变文件哈希值】直接处理没文件
