### ISSUE TITLE
添加文件夹导出结果包含文件夹名称导致校验不成功

### ISSUE THREAD

**Issue by Trudeau566** [hrpzcf/HashCalculator#71]
以下是添加文件夹导出结果，黄色区域是文件夹名称，必须去除才能校验成功。
![PixPin_2024-05-23_13-27-32](https://github.com/hrpzcf/HashCalculator/assets/118544592/5f89421c-4c7a-4595-9881-bb1271c18726)

**Comment by Trudeau566** [comment]
> `结果文件`应该放在与 `yt_clipper`

结果文件应该放在与yt_clipper文件夹相同的目录下.
我试了依然不行。把$relpath$改为 $name$倒是可以校验成功

**Comment by hrpzcf** [comment]
> > `结果文件`应该放在与 `yt_clipper`
> 
> 结果文件应该放在与yt_clipper文件夹相同的目录下. 我试了依然不行。把$relpath$改为 name倒是可以校验成功

 实际测试：
![动画](https://github.com/hrpzcf/HashCalculator/assets/58855572/3fa04354-60bc-4fc4-8b68-b70dc4e7a328)

**Comment by Trudeau566** [comment]
> > > `结果文件`应该放在与  `yt_clipper`
> > 
> > 
> > 结果文件应该放在与yt_clipper文件夹相同的目录下. 我试了依然不行。把$relpath$改为 name倒是可以校验成功
> 
> 实际测试： ![动画](https://private-user-images.githubusercontent.com/58855572/333642086-3fa04354-60bc-4fc4-8b68-b70dc4e7a328.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTA0NTYsIm5iZiI6MTcxNjU5MDE1NiwicGF0aCI6Ii81ODg1NTU3Mi8zMzM2NDIwODYtM2ZhMDQzNTQtNjBiYy00ZmM0LThiNjgtYjcwZGM0ZTdhMzI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTE3OTYxYWM5ZWU5MGM1YTU4MzRhYmJhYmNmZTk1MGNhZDVhYjRkMjQxMTJlZWUxMmQ0N2I2OGNlZDMzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.osbcJgGKn8uIXTOB2rya8eWzJqxMK7vON7OCmX_HUZY) [ ![动画](https://private-user-images.githubusercontent.com/58855572/333642086-3fa04354-60bc-4fc4-8b68-b70dc4e7a328.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTA0NTYsIm5iZiI6MTcxNjU5MDE1NiwicGF0aCI6Ii81ODg1NTU3Mi8zMzM2NDIwODYtM2ZhMDQzNTQtNjBiYy00ZmM0LThiNjgtYjcwZGM0ZTdhMzI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTE3OTYxYWM5ZWU5MGM1YTU4MzRhYmJhYmNmZTk1MGNhZDVhYjRkMjQxMTJlZWUxMmQ0N2I2OGNlZDMzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.osbcJgGKn8uIXTOB2rya8eWzJqxMK7vON7OCmX_HUZY) ](https://private-user-images.githubusercontent.com/58855572/333642086-3fa04354-60bc-4fc4-8b68-b70dc4e7a328.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTA0NTYsIm5iZiI6MTcxNjU5MDE1NiwicGF0aCI6Ii81ODg1NTU3Mi8zMzM2NDIwODYtM2ZhMDQzNTQtNjBiYy00ZmM0LThiNjgtYjcwZGM0ZTdhMzI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTE3OTYxYWM5ZWU5MGM1YTU4MzRhYmJhYmNmZTk1MGNhZDVhYjRkMjQxMTJlZWUxMmQ0N2I2OGNlZDMzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.osbcJgGKn8uIXTOB2rya8eWzJqxMK7vON7OCmX_HUZY) [ ](https://private-user-images.githubusercontent.com/58855572/333642086-3fa04354-60bc-4fc4-8b68-b70dc4e7a328.gif?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1OTA0NTYsIm5iZiI6MTcxNjU5MDE1NiwicGF0aCI6Ii81ODg1NTU3Mi8zMzM2NDIwODYtM2ZhMDQzNTQtNjBiYy00ZmM0LThiNjgtYjcwZGM0ZTdhMzI4LmdpZj9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA1MjQlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNTI0VDIyMzU1NlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhMTE3OTYxYWM5ZWU5MGM1YTU4MzRhYmJhYmNmZTk1MGNhZDVhYjRkMjQxMTJlZWUxMmQ0N2I2OGNlZDMzNzMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.osbcJgGKn8uIXTOB2rya8eWzJqxMK7vON7OCmX_HUZY)

可以了，是我自己搞错了不好意思
