### ISSUE TITLE
建议添加校验依据的输入格式

### ISSUE THREAD

**Issue by mailrider** [hrpzcf/HashCalculator#95]
最近在使用115网盘脚本 （https://greasyfork.org/zh-CN/scripts/400550） 时发现脚本的四种输出格式在HashCalculator上都无法识别，脚本的输出格式分别为SHA1 *路径（与 sha1sum 输出相同），SHA1|文件大小|路径，SHA1|路径和SHA1 路径，想问问大佬能否添加其中任意一种输入格式来方便校验，谢谢大佬

**Comment by hrpzcf** [comment]
方便贴出4种输出格式例子吗？有输出格式的话比较好写解析表达式。不过如果你会正则表达式的话我建议还是自己写表达式添加到解析方案里，因为下个内置这些解析方案的版本不会很快发布。

**Comment by mailrider** [comment]
以文件【s2 ep01.mp4】为例，脚本的四种输出格式如下所示：
① C6CFF49EE95A18411BCB1180442F8B93F599F6A1 *s2 ep01.mp4
② C6CFF49EE95A18411BCB1180442F8B93F599F6A1|403051546|s2 ep01.mp4
③ C6CFF49EE95A18411BCB1180442F8B93F599F6A1|s2 ep01.mp4
④ C6CFF49EE95A18411BCB1180442F8B93F599F6A1 s2 ep01.mp4
很遗憾作为小白并不会写表达式，而且也并不急着使用，所以就有劳大佬空闲时帮忙适配一下了，谢谢大佬

**Comment by hrpzcf** [comment]
理论上输出格式 ① 可以被 “通用二” 解析方案匹配到，我试了一下可以匹配到，请问 “无法识别” 具体是什么状况？

**Comment by mailrider** [comment]
请问“通用二” 解析方案具体是指哪个默认算法呢？
我的校验流程如下：打开软件指定SHA1算法后，再选择文件夹进行文件的哈希值批量计算，软件搜索到文件并完成计算后，再在底下的校验依据处粘贴通过脚本得到的SHA1进行批量校验，最后校验结果列显示灰色，表示已成功但无关联
![哈希值](https://github.com/user-attachments/assets/d0dffffa-8c03-4119-be57-49850da8b365)

**Comment by hrpzcf** [comment]
> 请问“通用二” 解析方案具体是指哪个默认算法呢？ 我的校验流程如下：打开软件指定SHA1算法后，再选择文件夹进行文件的哈希值批量计算，软件搜索到文件并完成计算后，再在底下的校验依据处粘贴通过脚本得到的SHA1进行批量校验，最后校验结果列显示灰色，表示已成功但无关联 ![哈希值](https://private-user-images.githubusercontent.com/141027250/356819382-d0dffffa-8c03-4119-be57-49850da8b365.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjMzMDUyNzgsIm5iZiI6MTcyMzMwNDk3OCwicGF0aCI6Ii8xNDEwMjcyNTAvMzU2ODE5MzgyLWQwZGZmZmZhLThjMDMtNDExOS1iZTU3LTQ5ODUwZGE4YjM2NS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwODEwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDgxMFQxNTQ5MzhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0zOTk3NjhiNjc5MmIzZGFlNWYwY2IwNzIwZGRjODM3ZGExMDA0M2FkODMzOWI2YjY4ZTA4MjA1OTMxZjRkMDU0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.GoQuEKAzm_OrKtAbeU1T3HSbyddfabgu8kFuYgEjfgU)

因为你计算的文件名是 01.mp4、02.mp4 的形式，而你输入校验依据输入框的内容是有具体的文件名的，所以 HashCalculator 会认为它们之间没有关联。你应该确保表格中的文件的文件名与校验依据输入框的文件名一致，在这种情况下，如果对应文件的哈希值一致，则校验结果列会显示为绿色（以匹配），哈希值不一致则显示为灰色（无关联），显示为灰色而不显示红色，是因为输入校验依据输入框的内容没有指明算法，HashCalculator 并不知道这些内容是什么算法算出来的，所以只能给出无关联的结果（这是软件缺陷，下个版本会改进为显示红色--不匹配的结果，具体见 issues #97 ）。

**Comment by mailrider** [comment]
问题已解决，谢谢大佬
