### ISSUE TITLE
自定义右键菜单列出的算法

### ISSUE THREAD

**Issue by Private0xCC** [hrpzcf/HashCalculator#98]
现在右键菜单会列出所有支持的算法以及默认算法，能不能增加一个设置项，支持设置哪些算法显示在右键菜单中。
算法太多，无法快速选中我想要的算法，而默认算法在第一项，我需要向上移动鼠标很远才能选中默认算法。

**Comment by hrpzcf** [comment]
在安装右键菜单的页面下面有一个“右键菜单配置文件编辑器”，打开即可自定义右键菜单。
